### ISSUE TITLE
[Bug]: Display issues for long lists, subtasks, and concurrency

### ISSUE THREAD

**Issue by ArthurGoupil** [listr2/listr2#720]
### Replication of the Problem

In the `subtasks.example.ts`, duplicate the tasks `This task will execute.` a high number of times so that the list is bigger than terminal height (put a distinctive title for 3 first tasks).
Set global concurrency to 3.

### Problem

With a very long list (probably which makes the list larger than terminal height), subtasks, and concurrency, the first elements of the lists are not always visible.

### Environment

Node20, terminal Warp

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by masad-frost** [comment]
Quick correction here, subtasks aren't necessarily a factor here, you just need a terminal shorter than the list + output.

Here's a simple repro

```ts
import { delay, Listr, type ListrTask } from "listr2";

const titles = [
  "To Kill a Mockingbird",
  "1984",
  "The Great Gatsby",
  "The Catcher in the Rye",
  "Moby-Dick",
  "Pride and Prejudice",
  "War and Peace",
  "The Odyssey",
  "Great Expectations",
  "Crime and Punishment",
  "The Brothers Karamazov",
  "Madame Bovary",
  "Jane Eyre",
  "Wuthering Heights",
  "Brave New World",
  "Animal Farm",
  "Ulysses",
  "Love in the Time of Cholera",
  "One Hundred Years of Solitude",
  "The Divine Comedy",
  "Don Quixote",
  "The Iliad",
  "Les Misérables",
  "A Tale of Two Cities",
  "Catch-22",
  "The Hobbit",
  "The Lord of the Rings",
  "Frankenstein",
];

console.log(
  `we should see ${titles.slice(0, 3)} on top`,
);

const tasks = new Listr(
  titles.map(
    (title): ListrTask => ({
      title,
      rendererOptions: {
        outputBar: Infinity,
        persistentOutput: true,
      },
      task: async (ctx, task) => {
        await delay(500);
        task.output = "hello";
        task.output = "world";
        await delay(500);
      },
    }),
  ),
  {
    concurrent: 5,
  },
);

await tasks.run();
```

If the terminal is shorter than the rendered task list and we have concurrent tasks emitting output, you'll notice that the top tasks start getting pushed up.

Here's how it starts off:
![image](https://github.com/listr2/listr2/assets/1994028/f433c950-efdd-4ace-9426-df30a51fdcff)


Then tasks start getting pushed up
![image](https://github.com/listr2/listr2/assets/1994028/31a1e232-0242-4497-a10c-b82093ca49f6)

Good news is that when all tasks are done, the renderer fixes things.

**Comment by masad-frost** [comment]
@cenk1cenk2 Sent a one time sponsorship, i'll double it if the issue is resolved in the next week :)

**Comment by masad-frost** [comment]
Turns out concurrency isn't necessary to reproduce, just any task list that's long enough leads to this behavior.

**Comment by ArthurGoupil** [comment]
Thanks for the precisions @masad-frost !

**Comment by cenk1cenk2** [comment]
Dear @ArthurGoupil and @masad-frost,

Thank you for reporting this, but this is a known issue on my side.

As far as I know, and please correct me if I am wrong, you can not take control of the terminal outside of the lines that you are currently seeing and in the scrollback area. This usually corresponds to visual artifacts in lines, since it can not properly redraw with the given state. So this is kind of the problem of the underlying library not being able to sync the state it has with the output, where I already tried to swap it out before with no avail as I have tried to describe [here](https://listr2.kilic.dev/repository/contributions.html#updating-renderer).

What I can propose is we can watch the terminal height and depending on that we can truncate the first lines if the height of the tasks exceeds the terminal height so that the incoming data to the underlying library, but I am not sure if it would be enough to handle resize events.

**Comment by vladshcherbin** [comment]
Oh man, I've hit 2/2 missing pieces I would need 😭

I have around 200 subtasks and they all don't fit the screen. The result is that first tasks are pushed top and I can't see them. All of them have prompts inside ... 🙈

Any workaround for this? I'd be happy to see 1 task at a time or at least see top / current executed one

**Comment by vladshcherbin** [comment]
Same issue raised before - https://github.com/listr2/listr2/issues/296

**Comment by cenk1cenk2** [comment]
The flicker and heavy re-rendering on large lists is improved in v11 (currently on the beta channel): the default renderer moved to `log-update` v8 with partial/differential rendering (#781). The other half, where the first items scroll out of view once the list is taller than the terminal, comes from clipping the live frame to the terminal height. An explicit windowing policy to keep chosen tasks visible was evaluated and not adopted for v11, so that remains a known limitation. Leaving this open to track it.
